spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sppoti
    username: root
    password:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    poolSize: 10
    host: localhost
    dbName: sppoti
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: localhost
    password: secret
    port: 6379

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://sppoti-databse.cft4b56rinat.eu-west-1.rds.amazonaws.com:3306/sppoti
    username: sppoti
    password: sppoti2017
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    poolSize: 10
    host: sppoti-databse.cft4b56rinat.eu-west-1.rds.amazonaws.com
    dbName: sppoti
    initialize: false
  redis:
    host: localhost
    password: secret
    port: 6379

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_SERVICE}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    host: ${MYSQL_HOST_SERVICE}
    dbName: ${MYSQL_DATABASE}
    driverClassName: com.mysql.jdbc.Driver
    poolSize: 10
    initialize: true
  redis:
    host: ${REDIS_HOST_SERVICE}
    password: secret
    port: 6379