version: '3'

services:

  nginx:
      image: nginx
      ports:
        - "80:80"
      container_name: nginx
      env_file:
        - ./common.env

  db:
      image: mysql
      container_name: mysql
      volumes:
            - db_data:/var/lib/mysql
      env_file:
        - ./common.env

  redis:
    image: redis

  sppoti:
      build: .
      image: sppoti
      depends_on:
#            - redis
            - db
      env_file:
        - ./common.env

volumes:
  db_data: