version: '3.1'

services:

  nginx:
      image: cocoda/sppoti-front
      depends_on:
          - sppoti
#      build:
#        context: <path_to_front>
      container_name: sppoti-front
      ports:
          - 80:80
#      volumes:
#        - nginx_data:/var/log/nginx

  db:
      image: mysql:5.7
      container_name: mysql
      ports:
        - 3306:3306
#      volumes:
#            - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        MYSQL_PASSWORD_FILE: /run/secrets/db_password
        MYSQL_USER: sppoti
        MYSQL_DATABASE: sppoti
      secrets:
             - db_root_password
             - db_password

  redis:
    image: redis
#    volumes:
#        - redis_data:/data

  aws-getway:
    image: wdjenane/aws-getway
    ports:
        - 8181:8181

  sppoti:
      image: wdjenane/sppoti
#      ports:
#        - 8080:8080
      depends_on:
            - redis
            - db
      environment:
        REDIS_HOST_SERVICE: redis
        MYSQL_HOST_SERVICE: db
        MYSQL_USER: sppoti
        MYSQL_PASSWORD: aaaaaaa
        MYSQL_PASSWORD_FILE: /run/secrets/db_password
        MYSQL_DATABASE: sppoti
#      volumes:
#            - sppoti_data:/var/log/sppoti
      secrets:
            - db_password

secrets:
   db_password:
     file: ./secrets/db_password.txt
   db_root_password:
     file: ./secrets/db_root_password.txt
