version: '3'

services:

  nginx:
      image: nginx
      ports:
        - "80:80"

  db:
      image: mysql
      volumes:
            - db_data:/var/lib/mysql

  redis:
    image: redis

  sppoti:
      image: sppoti
      depends_on:
#            - redis
            - db
      restart: always

volumes:
  db_data: