version: '3'

services:

  reverseproxy:
      image: reverseproxy
      container_name: reverseproxy
      depends_on:
          - sppoti
      ports:
        - 80:80

  nginx:
      image: sppoti-front
      container_name: sppoti-front
      depends_on:
          - reverseproxy
      volume:
        - nginx_data:/var/log/nginx

  db:
      image: mysql
      container_name: mysql
      volumes:
            - db_data:/var/lib/mysql
      env_file:
        - ./common.env

  redis:
    image: redis
    volume:
        - redis_data:/data

  sppoti:
      build: .
      image: sppoti-back
      ports:
        - 8080:8080
      depends_on:
            - redis
            - db
      env_file:
        - ./common.env
      volume:
        - sppoti_data:/var/log/sppoti

volumes:
  db_data:
  redis_data:
  sppoti_data:
  nginx_data: